### ISSUE TITLE
Webbased rebasing of PR's is not possible

### ISSUE THREAD

**Issue by portly-halicore-76** [belastingdienst/opr-paas#25]
When using the GitHub UI to rebase a PR, I get an error stating there are unsigned commits, eventhough my PR contains only signed commits. It is rather cumbersome to use my local machine to work around this issue, please fix.

**Comment by hikarukin** [comment]
Though I hate to say it, I don't think there's much we can do about this after all the testing we did?

So I'm closing this to clean up. Feel free to reopen if you disagree.
